#!/bin/bash

docker run --rm repronim/neurodocker:0.7.0 generate docker \
  --base poldracklab/mriqc:0.15.1 -p apt \
  --miniconda use_env=base \
    conda_install="atlassian-python-api " \
  > Dockerfile
